namespace LibVds.Proto
{
    public enum MessageType
    {
        Meldung_Ein = 0x00,
        Meldung_Aus = 0x80,
        Brandmeldung_Ausgeloest = 0x10,
        Brandmeldung_Zurueckgesetzt = 0x90,
        Brand_manueller_Melder_Ausgeloest = 0x11,
        Brand_manueller_Melder_Zurueckgesetzt = 0x91,
        Brand_automatischer_Melder_Ausgeloest = 0x12,
        Brand_automatischer_Melder_Zurueckgesetzt = 0x92,
        Brandmeldung_aus_Loeschanlage_Ausgeloest = 0x13,
        Brandmeldung_aus_Loeschanlage_Zurueckgesetzt = 0x93,

        Ueberfall_Einbruchmeldung_Ausgeloest = 0x20,
        Ueberfall_Einbruchmeldung_Zurueckgesetzt = 0xA0,
        Ueberfall_Ausgesloest = 0x21,
        Ueberfall_Zurueckgesetzt = 0xA1,
        Einbruch_Ausgeloest = 0x22,
        Einbruch_Zurueckgesetzt = 0xA2,
        Sabotage_Ausgeloest = 0x23,
        Sabotage_Zurueckgesetzt = 0xA3,
        Geiselnahme_Ausgeloest = 0x24,
        Geiselnahme_Zurueckgesetzt = 0xA4,
        Bereichsmeldung_Ueberfall_Einbruch_Ausgeloest = 0x2F,
        Bereichsmeldung_Ueberfall_Einbruch_Zurueckgesetzt = 0xAF,

        Stoerungsmeldungen_Ausgeloest = 0x30,
        Stoerungsmeldungen_Zurueckgesetzt = 0xB0,
        Stoerung_Primaerleitung_Ausgeloest = 0x31,
        Stoerung_Primaerleitung_Zurueckgesetzt = 0xB1,
        Stoerung_Netz_Ausgeloest = 0x32,
        Stoerung_Netz_Beseitigt = 0xB2,
        Stoerung_Batterie_Ausgeloest = 0x33,
        Stoerung_Batterie_Zurueckgesetzt = 0xB3,
        Stoerung_Uebertragungsweg_Ausgeloest = 0x34,
        Stoerung_Uebertragungsweg_Zurueckgesetzt = 0xB4,
        Stoerung_Erdschluss_Ausgeloest = 0x35,
        Stoerung_Erdschluss_Zurueckgesetzt = 0xB5,
        Stoerung_Testmeldung_Nicht_Erhalten =0x36,
        Stoerung_Testmeldung_Wieder_In_Ordnung = 0xB6,
        Stoerung_Energieversorgung_UeG_Letztmalig = 0x37,
        Stoerung_Energieversorgung_Wieder_In_Ordnung = 0xB7,
        Stoerung_Pufferueberlauf_Ausgeloest =0x38,
        Stoerung_Pufferueberlauf_Zurueckgesetzt = 0xB8,
        Nicht_Abgesetzte_Meldung_Ausgeloest = 0x39,
        Nicht_Abgesetzte_Meldung_Zurueckgesetzt = 0xB9,
        Stoerung_Uebertragungsweg_1_Ausgeloest = 0x3A,
        Stoerung_Uebertragungsweg_1_Wieder_In_Ordnung = 0xBA,
        Stoerung_Uebertragungsweg_2_Ausgeloest = 0x3B,
        Stoerung_Uebertragungsweg_2_Wieder_In_Ordnung = 0xBB,

        Technische_Meldung_Ausgeloest = 0x40,
        Technische_Meldung_Zurueckgesetzt = 0xC0,
        Technikalarm_Ausgeloest =0x41,
        Technikalarm_Zurueckgesetzt = 0xC1,
        Notmeldung_Allgemein_Ausgeloest = 0x48,
        Notmeldung_Allgemein_Zurueckgesetzt = 0xC8,
        Notmeldung_1_Ausgeloest = 0x4A,
        Notmeldung_1_Zurueckgesetzt = 0xC9,
        Notmeldung_2_Ausgeloest = 0x4B,
        Notmeldung_2_Zurueckgesetzt = 0xCA,
        Notmeldung_3_Ausgeloest = 0x4C,
        Notmeldung_3_Zurueckgesetzt = 0xCB,
        Notmeldung_4_Ausgeloest = 0x4D,
        Notmeldung_4_Zurueckgesetzt = 0xCC,

        Geraetemeldung_Aktivieren = 0x50,
        Geraetemeldung_Zuruecknehmen = 0xD0,
        Abschaltung_Aktivieren = 0x51,
        Abschaltung_Zuruecknehmen = 0xD1,
        Ruecksetzen_Aktivieren = 0x52,
        Wiederanlauf_Neustart_Aktivieren = 0x53,
        Meldungspufferueberlauf_Aufgetreten = 0x54,
        Systemstoerung_Aufgetreten = 0x55,
        Deckelkontakt_Offen = 0x56,
        Deckelkontakt_Geschlossen = 0xD6,

        Zustandsmeldunge_Ein = 0x60,
        Zustandsmeldungen_ = 0xE0,
        Sicherungsbereich_Scharf = 0x61,
        Sicherungsbereich_Unscharf = 0xE1,
        Internbereich_Ein = 0x62,
        Interbereich_Aus = 0xE2,
        Revisionszustand_Ein = 0x63,
        Revisionszustand_Aus = 0xE3,
        Tagbetrieb_Ein = 0x64,
        Tagbetrieb_Aus = 0xE4,
        Firmenspezifisch_Freie_Meldung_1_Ausgeloest = 0x71,
        Firmenspezifisch_Freie_Meldung_1_Zurueckgesetzt = 0xF1



    }
}